# Generated by Django 2.0 on 2022-10-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20221004_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
